import { ActionForm, DeleteForm } from '@/components/admin-action-form';
import { CopyMediaUrl, MediaUpload } from '@/components/media-upload';
import { deleteMedia, saveMedia } from '@/app/admin/actions';
import { requireAdmin } from '@/lib/auth';
import { createSupabaseServerClient } from '@/lib/supabase-server';
import { getMediaUsage } from '@/lib/media-usage';
import type { MediaAsset } from '@/lib/cms';

export const dynamic = 'force-dynamic';

function MediaForm({ asset }: { asset?: MediaAsset }) {
  return <ActionForm action={saveMedia}><input type="hidden" name="id" value={asset?.id || ''} /><input type="hidden" name="original_filename" value={asset?.original_filename || ''} /><div className="admin-form__grid"><div className="admin-field"><label>Media name<input name="name" maxLength={140} defaultValue={asset?.name} required /></label></div><div className="admin-field"><label>Alt text<input name="alt_text" maxLength={250} defaultValue={asset?.alt_text} required /></label></div><div className="admin-field"><label>Image title<input name="title" maxLength={180} defaultValue={asset?.title || ''} /></label></div><div className="admin-field"><label>Caption<textarea name="caption" maxLength={500} defaultValue={asset?.caption || ''} /></label></div><div className="admin-field"><label>Image URL<input name="url" type="text" defaultValue={asset?.url} placeholder="https://… or /assets/images/…" required /></label></div><div className="admin-field"><label>MIME type<input name="mime_type" defaultValue={asset?.mime_type || 'image/webp'} required /></label></div><div className="admin-field"><label>Width<input name="width" type="number" min="1" defaultValue={asset?.width || ''} /></label></div><div className="admin-field"><label>Height<input name="height" type="number" min="1" defaultValue={asset?.height || ''} /></label></div><div className="admin-field"><label>Storage<select name="storage_provider" defaultValue={asset?.storage_provider || 'public'}><option value="public">Bundled public asset</option><option value="vercel_blob">Vercel Blob</option></select></label></div></div></ActionForm>;
}

export default async function MediaAdminPage() {
  await requireAdmin();
  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.from('media').select('*').order('created_at', { ascending: false });
  const assets = (data ?? []) as MediaAsset[];
  const usage = await getMediaUsage(assets);
  return <><header className="admin-header"><div><h1>Media library</h1><p>Persistent image storage for the website. Upload to Vercel Blob, keep descriptive metadata, reuse existing images, and replace files without leaving broken public references.</p></div></header><section className="admin-panel"><h2>Upload a new image</h2><MediaUpload /><p className="admin-help">Accepted: JPEG, PNG, WebP, or GIF. Maximum size: 10 MB. New uploads are stored in persistent Vercel Blob storage, not the app filesystem.</p></section><section className="admin-panel"><h2>Media library</h2>{error && <p className="admin-notice admin-notice--error">Media could not be loaded. Apply the media metadata migration if the database is out of date.</p>}{assets.length === 0 ? <div className="admin-empty">No media records have been created.</div> : <div className="media-library-grid">{assets.map((asset) => { const assetUsage = usage[asset.id] || { count: 0, locations: [] }; return <article className="media-card" key={asset.id}><div className="media-card__preview"><img src={asset.url} alt={asset.alt_text} width="720" height="480" /></div><div className="media-card__body"><div className="media-card__heading"><div><h3>{asset.title || asset.name}</h3><p>{asset.original_filename || asset.name}</p></div><span className={`media-badge ${asset.storage_provider === 'vercel_blob' ? 'media-badge--persistent' : ''}`}>{asset.storage_provider === 'vercel_blob' ? 'Persistent' : 'Bundled'}</span></div><p className="media-card__alt"><strong>Alt:</strong> {asset.alt_text}</p>{asset.caption && <p className="media-card__caption">{asset.caption}</p>}<p className="media-card__meta">{asset.mime_type} · {asset.width && asset.height ? `${asset.width} × ${asset.height} · ` : ''}{new Intl.DateTimeFormat('en-US', { dateStyle: 'medium' }).format(new Date(asset.created_at))}</p><p className={`media-usage ${assetUsage.count ? 'media-usage--used' : ''}`}><strong>{assetUsage.count ? `${assetUsage.count} reference${assetUsage.count === 1 ? '' : 's'}` : 'Not currently referenced'}</strong>{assetUsage.locations.length > 0 && <> · {assetUsage.locations.slice(0, 2).join(' · ')}</>}</p><div className="media-card__actions"><CopyMediaUrl url={asset.url} /><details><summary className="admin-button admin-button--quiet">Edit metadata</summary><div className="admin-panel"><MediaForm asset={asset} /></div></details><details><summary className="admin-button admin-button--quiet">Replace image</summary><div className="admin-panel"><MediaUpload replace={asset} /></div></details>{assetUsage.count === 0 ? <DeleteForm action={deleteMedia} id={asset.id} /> : <span className="admin-button admin-button--disabled" title="Remove public references before deleting this image">Delete protected</span>}</div></div></article>; })}</div>}</section></>;
}
