import { ActionForm, DeleteForm } from '@/components/admin-action-form';
import { deleteCardGame, saveCardGame, saveCardsContent } from '@/app/admin/actions';
import { requireAdmin } from '@/lib/auth';
import { createSupabaseServerClient } from '@/lib/supabase-server';
import { fallbackCardsContent } from '@/lib/fallback-content';
import type { CardGame, CardsContent } from '@/lib/cms';

export const dynamic = 'force-dynamic';

function CardsContentForm({ content }: { content: CardsContent }) {
  return <ActionForm action={saveCardsContent}><div className="admin-form__grid"><div className="admin-field"><label>Cards eyebrow<input name="eyebrow" maxLength={120} defaultValue={content.eyebrow} required /></label></div><div className="admin-field"><label>Cards title<input name="title" maxLength={180} defaultValue={content.title} required /></label></div></div><div className="admin-field"><label>Cards description<textarea name="description" maxLength={1200} defaultValue={content.description} required /></label></div><div className="admin-form__grid"><div className="admin-field"><label>Magic eyebrow<input name="magic_eyebrow" maxLength={120} defaultValue={content.magic_eyebrow} required /></label></div><div className="admin-field"><label>Magic title<input name="magic_title" maxLength={180} defaultValue={content.magic_title} required /></label></div></div><div className="admin-field"><label>Magic description<textarea name="magic_description" maxLength={1200} defaultValue={content.magic_description} required /></label></div><div className="admin-form__grid"><div className="admin-field"><label>Event wording<input name="magic_event_wording" maxLength={500} defaultValue={content.magic_event_wording} required /></label></div><div className="admin-field"><label>Event time<input name="magic_event_time" maxLength={120} defaultValue={content.magic_event_time} required /></label></div><div className="admin-field"><label>Event frequency<input name="magic_event_frequency" maxLength={120} defaultValue={content.magic_event_frequency} required /></label></div></div><div className="admin-field"><label>Prerelease wording<textarea name="magic_prerelease_text" maxLength={500} defaultValue={content.magic_prerelease_text} required /></label></div><div className="admin-field"><label>Cards announcement (optional)<textarea name="announcement" maxLength={500} defaultValue={content.announcement || ''} /></label></div><div className="admin-field"><label>Featured game slug<input name="featured_game_slug" maxLength={80} defaultValue={content.featured_game_slug || ''} placeholder="magic" /></label></div></ActionForm>;
}

function CardForm({ game }: { game?: CardGame }) {
  return <ActionForm action={saveCardGame}><input type="hidden" name="id" value={game?.id || ''} /><div className="admin-form__grid"><div className="admin-field"><label>Game name<input name="name" maxLength={120} defaultValue={game?.name} required /></label></div><div className="admin-field"><label>URL slug<input name="slug" maxLength={80} defaultValue={game?.slug} required /></label></div><div className="admin-field"><label>Image URL<input name="image_url" type="text" defaultValue={game?.image_url || ''} placeholder="/assets/images/… or https://…" /></label></div><div className="admin-field"><label>Image alt text<input name="image_alt" maxLength={250} defaultValue={game?.image_alt || ''} /></label></div><div className="admin-field"><label>CTA text<input name="cta_label" maxLength={100} defaultValue={game?.cta_label || ''} /></label></div><div className="admin-field"><label>CTA link<input name="cta_href" maxLength={300} defaultValue={game?.cta_href || '/visit.html'} /></label></div><div className="admin-field"><label>Display order<input name="sort_order" type="number" min="0" max="999" defaultValue={game?.sort_order ?? 0} required /></label></div></div><div className="admin-field"><label>Description<textarea name="description" maxLength={700} defaultValue={game?.description} required /></label></div><label className="admin-checkbox"><input name="active" type="checkbox" defaultChecked={game?.active ?? true} /> Show on the public Cards page</label></ActionForm>;
}

export default async function CardsAdminPage() {
  await requireAdmin();
  const supabase = await createSupabaseServerClient();
  const [contentResult, gamesResult] = await Promise.all([supabase.from('card_page_content').select('*').eq('id', 'default').maybeSingle(), supabase.from('card_games').select('*').order('sort_order')]);
  const content = (contentResult.data || fallbackCardsContent) as CardsContent;
  const games = (gamesResult.data ?? []) as CardGame[];
  return <><header className="admin-header"><div><h1>Cards</h1><p>Manage the public Cards page, card games, Magic programming, event wording, announcements, images, and display order.</p></div></header><section className="admin-panel"><h2>Cards page and Magic content</h2><CardsContentForm content={content} /></section><section className="admin-panel"><h2>Add card game</h2><CardForm /></section><section className="admin-panel"><h2>Card-game listings</h2>{games.length === 0 ? <div className="admin-empty">No card games are published yet.</div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Preview</th><th>Game</th><th>Status</th><th>Order</th><th>Actions</th></tr></thead><tbody>{games.map((game) => <tr key={game.id}><td>{game.image_url && <img src={game.image_url} alt={game.image_alt || ''} width="80" height="54" style={{ objectFit: 'cover', borderRadius: 4 }} />}</td><td><strong>{game.name}</strong><br /><small>{game.description}</small></td><td>{game.active ? 'Public' : 'Hidden'}</td><td>{game.sort_order}</td><td className="actions"><details><summary className="admin-button admin-button--quiet">Edit</summary><div className="admin-panel"><CardForm game={game} /></div></details><DeleteForm action={deleteCardGame} id={game.id} /></td></tr>)}</tbody></table></div>}</section></>;
}
