'use client';

import { useActionState, useMemo, useState } from 'react';
import type { ActionState, Json, PageSection } from '@/lib/cms';
import { initialActionState } from '@/lib/cms';
import { saveHomepage } from '@/app/admin/actions';

type Content = Record<string, Json>;
type SectionMap = Record<string, Content>;

function text(content: Content, key: string, fallback = '') { return typeof content[key] === 'string' ? content[key] as string : fallback; }
function strings(content: Content, key: string) { return Array.isArray(content[key]) ? (content[key] as Json[]).filter((value): value is string => typeof value === 'string') : []; }

function Field({ label, name, value, onChange, multiline = false, help }: { label: string; name: string; value: string; onChange: (value: string) => void; multiline?: boolean; help?: string }) {
  return <div className="admin-field"><label htmlFor={`homepage-${name}`}>{label}</label>{multiline ? <textarea id={`homepage-${name}`} name={name} value={value} onChange={(event) => onChange(event.target.value)} /> : <input id={`homepage-${name}`} name={name} value={value} onChange={(event) => onChange(event.target.value)} />}{help && <small>{help}</small>}</div>;
}

function ArrayField({ label, values, onChange, help }: { label: string; values: string[]; onChange: (values: string[]) => void; help?: string }) {
  return <div className="admin-field"><label>{label}</label>{values.map((value, index) => <input key={`${index}-${value}`} aria-label={`${label} ${index + 1}`} value={value} onChange={(event) => onChange(values.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} />)}<button className="admin-button admin-button--quiet" type="button" onClick={() => onChange([...values, ''])}>Add another</button>{help && <small>{help}</small>}</div>;
}

export function HomepageEditor({ sections }: { sections: PageSection[] }) {
  const initial = Object.fromEntries(sections.map((section) => [section.key, section.content])) as SectionMap;
  const [draft, setDraft] = useState<SectionMap>(initial);
  const [state, formAction, pending] = useActionState(saveHomepage, initialActionState);
  const hero = draft.hero || {};
  const intro = draft.intro || {};
  const categories = draft.categories || {};
  const gallery = draft.gallery || {};
  const owner = draft.owner || {};
  const visit = draft.visit || {};
  const announcement = draft.announcement || {};
  const cta = draft.cta || {};
  const update = (key: string, field: string, value: Json) => setDraft((current) => ({ ...current, [key]: { ...(current[key] || {}), [field]: value } }));
  const previewTitle = text(hero, 'title', 'Every shelf is a new world.');
  const previewBody = text(hero, 'body', 'Your homepage hero description will appear here.');
  const previewImage = text(hero, 'imageUrl', '/assets/images/new-comics.webp');
  const previewCards = useMemo(() => (Array.isArray(categories.items) ? categories.items : []).filter((item): item is Record<string, Json> => Boolean(item) && typeof item === 'object' && !Array.isArray(item)), [categories.items]);

  return <div className="homepage-editor-layout"><form action={formAction} className="admin-form homepage-editor-form">
    <input type="hidden" name="hero" value={JSON.stringify(hero)} /><input type="hidden" name="intro" value={JSON.stringify(intro)} /><input type="hidden" name="categories" value={JSON.stringify(categories)} /><input type="hidden" name="gallery" value={JSON.stringify(gallery)} /><input type="hidden" name="owner" value={JSON.stringify(owner)} /><input type="hidden" name="visit" value={JSON.stringify(visit)} /><input type="hidden" name="announcement" value={JSON.stringify(announcement)} /><input type="hidden" name="cta" value={JSON.stringify(cta)} />
    {state.status !== 'idle' && <p className={`admin-notice admin-notice--${state.status}`} role="status">{state.message}</p>}
    <section className="admin-panel"><h2>Hero</h2><div className="admin-form__grid"><Field label="Eyebrow" name="hero-eyebrow" value={text(hero, 'eyebrow')} onChange={(value) => update('hero', 'eyebrow', value)} /><Field label="Title" name="hero-title" value={text(hero, 'title')} onChange={(value) => update('hero', 'title', value)} /><Field label="Emphasis" name="hero-emphasis" value={text(hero, 'emphasis')} onChange={(value) => update('hero', 'emphasis', value)} help="Optional phrase highlighted in emerald." /><Field label="Image URL" name="hero-image" value={text(hero, 'imageUrl')} onChange={(value) => update('hero', 'imageUrl', value)} /></div><Field label="Description" name="hero-body" value={text(hero, 'body')} onChange={(value) => update('hero', 'body', value)} multiline /><div className="admin-form__grid"><Field label="Primary button label" name="hero-primary-label" value={text(hero, 'primaryLabel')} onChange={(value) => update('hero', 'primaryLabel', value)} /><Field label="Primary button link" name="hero-primary-href" value={text(hero, 'primaryHref')} onChange={(value) => update('hero', 'primaryHref', value)} /><Field label="Secondary button label" name="hero-secondary-label" value={text(hero, 'secondaryLabel')} onChange={(value) => update('hero', 'secondaryLabel', value)} /><Field label="Secondary button link" name="hero-secondary-href" value={text(hero, 'secondaryHref')} onChange={(value) => update('hero', 'secondaryHref', value)} /><Field label="Image alt text" name="hero-image-alt" value={text(hero, 'imageAlt')} onChange={(value) => update('hero', 'imageAlt', value)} /></div><ArrayField label="Hero highlights" values={strings(hero, 'meta')} onChange={(value) => update('hero', 'meta', value)} /></section>
    <section className="admin-panel"><h2>Introduction</h2><div className="admin-form__grid"><Field label="Eyebrow" name="intro-eyebrow" value={text(intro, 'eyebrow')} onChange={(value) => update('intro', 'eyebrow', value)} /></div><ArrayField label="Stacked title lines" values={strings(intro, 'titleLines')} onChange={(value) => update('intro', 'titleLines', value)} /><ArrayField label="Introduction paragraphs" values={strings(intro, 'body')} onChange={(value) => update('intro', 'body', value)} /></section>
    <section className="admin-panel"><h2>Homepage section headings</h2><div className="admin-form__grid"><Field label="Categories eyebrow" name="categories-eyebrow" value={text(categories, 'eyebrow')} onChange={(value) => update('categories', 'eyebrow', value)} /><Field label="Categories title" name="categories-title" value={text(categories, 'title')} onChange={(value) => update('categories', 'title', value)} /><Field label="Categories description" name="categories-intro" value={text(categories, 'intro')} onChange={(value) => update('categories', 'intro', value)} multiline /><Field label="Gallery eyebrow" name="gallery-eyebrow" value={text(gallery, 'eyebrow')} onChange={(value) => update('gallery', 'eyebrow', value)} /><Field label="Gallery title" name="gallery-title" value={text(gallery, 'title')} onChange={(value) => update('gallery', 'title', value)} /><Field label="Gallery description" name="gallery-intro" value={text(gallery, 'intro')} onChange={(value) => update('gallery', 'intro', value)} multiline /><Field label="Visit eyebrow" name="visit-eyebrow" value={text(visit, 'eyebrow')} onChange={(value) => update('visit', 'eyebrow', value)} /><Field label="Visit title" name="visit-title" value={text(visit, 'title')} onChange={(value) => update('visit', 'title', value)} /><Field label="Visit description" name="visit-intro" value={text(visit, 'intro')} onChange={(value) => update('visit', 'intro', value)} multiline /></div></section>
    <section className="admin-panel"><h2>Homepage announcement</h2><label className="admin-checkbox"><input type="checkbox" checked={Boolean(announcement.enabled)} onChange={(event) => update('announcement', 'enabled', event.target.checked)} /> Show this announcement publicly</label><div className="admin-form__grid"><Field label="Eyebrow" name="announcement-eyebrow" value={text(announcement, 'eyebrow')} onChange={(value) => update('announcement', 'eyebrow', value)} /><Field label="Title" name="announcement-title" value={text(announcement, 'title')} onChange={(value) => update('announcement', 'title', value)} /><Field label="Button label" name="announcement-label" value={text(announcement, 'buttonLabel')} onChange={(value) => update('announcement', 'buttonLabel', value)} /><Field label="Button link" name="announcement-href" value={text(announcement, 'buttonHref')} onChange={(value) => update('announcement', 'buttonHref', value)} /></div><Field label="Announcement text" name="announcement-body" value={text(announcement, 'body')} onChange={(value) => update('announcement', 'body', value)} multiline /></section>
    <section className="admin-panel"><h2>Owner story and CTA</h2><div className="admin-form__grid"><Field label="Owner section eyebrow" name="owner-eyebrow" value={text(owner, 'eyebrow')} onChange={(value) => update('owner', 'eyebrow', value)} /><Field label="Owner section title" name="owner-title" value={text(owner, 'title')} onChange={(value) => update('owner', 'title', value)} /><Field label="CTA eyebrow" name="cta-eyebrow" value={text(cta, 'eyebrow')} onChange={(value) => update('cta', 'eyebrow', value)} /><Field label="CTA title" name="cta-title" value={text(cta, 'title')} onChange={(value) => update('cta', 'title', value)} /><Field label="CTA description" name="cta-body" value={text(cta, 'body')} onChange={(value) => update('cta', 'body', value)} multiline /><Field label="CTA button label" name="cta-label" value={text(cta, 'buttonLabel')} onChange={(value) => update('cta', 'buttonLabel', value)} /><Field label="CTA button link" name="cta-href" value={text(cta, 'buttonHref')} onChange={(value) => update('cta', 'buttonHref', value)} /></div><ArrayField label="Owner story paragraphs" values={strings(owner, 'body')} onChange={(value) => update('owner', 'body', value)} /></section>
    <div className="admin-toolbar"><button className="admin-button admin-button--quiet" type="button" onClick={() => setDraft(initial)}>Cancel changes</button><button className="admin-button" type="submit" disabled={pending}>{pending ? 'Saving homepage…' : 'Save homepage content'}</button></div>
  </form><aside className="homepage-preview" aria-label="Homepage draft preview"><div className="homepage-preview__sticky"><span className="admin-preview-label">Live draft preview</span><div className="homepage-preview__hero"><p className="eyebrow">{text(hero, 'eyebrow')}</p><h2>{previewTitle}</h2><p>{previewBody}</p><a className="admin-button" href={text(hero, 'primaryHref', '/visit.html')}>{text(hero, 'primaryLabel', 'Visit the shop')}</a><img src={previewImage} alt={text(hero, 'imageAlt', 'Homepage hero preview')} /></div><div className="homepage-preview__intro"><span>{text(intro, 'eyebrow')}</span><h3>{strings(intro, 'titleLines').join(' ')}</h3><p>{strings(intro, 'body')[0]}</p></div><div className="homepage-preview__cards"><span>{text(categories, 'eyebrow')}</span><h3>{text(categories, 'title')}</h3>{previewCards.map((item, index) => <div key={index}><strong>{text(item, 'title', 'Card')}</strong><small>{text(item, 'label')}</small></div>)}</div>{Boolean(announcement.enabled) && <div className="homepage-preview__announcement"><span>{text(announcement, 'eyebrow')}</span><h3>{text(announcement, 'title')}</h3><p>{text(announcement, 'body')}</p></div>}</div></aside></div>;
}
