import type { BusinessHour, CatalogSection, CmsPageData, Json, PublicSiteData } from '@/lib/cms';

const setting = (value: string) => ({ key: value, value, label: value, updated_at: 'fallback' });

export const fallbackPublicSiteData: PublicSiteData = {
  settings: {
    business_name: 'Infinite Heroes Comics',
    business_description: 'Infinite Heroes Comics is the Main Street comic shop in Watertown, Connecticut — new comics and collectibles.',
    footer_summary: 'Comics and collectibles in Watertown, Connecticut.',
    address_line_1: '1098 Main St', address_line_2: 'Watertown, CT 06795', phone_display: '860-417-2559', phone_e164: '+18604172559', email: 'paul@infiniteheroes.net', time_zone: 'America/New_York', maps_url: 'https://maps.google.com/?q=1098+Main+St,+Watertown,+CT+06795', copyright_location: 'Watertown, Connecticut',
  },
  hours: [
    ['Monday', null, null, true], ['Tuesday', '11:00', '16:00', false], ['Wednesday', '11:00', '19:00', false], ['Thursday', '11:00', '19:00', false], ['Friday', '11:00', '19:00', false], ['Saturday', '11:00', '19:00', false], ['Sunday', '12:00', '17:00', false],
  ].map(([label, open_time, close_time, is_closed], index) => ({ id: `fallback-${index}`, day_of_week: index, label, open_time, close_time, is_closed, sort_order: index } as BusinessHour)),
  socials: [{ id: 'fallback-facebook', platform: 'facebook', label: 'Facebook', url: 'https://www.facebook.com/infiniteheroescomics/', sort_order: 10, active: true }, { id: 'fallback-instagram', platform: 'instagram', label: 'Instagram', url: 'https://www.instagram.com/infiniteheroescomics/', sort_order: 20, active: true }],
};

const page = (slug: string, title: string, description: string, sections: Array<{ key: string; label: string; section_type: PageDataType; content: Record<string, Json> }>): CmsPageData => ({ page: { id: `fallback-${slug}`, slug, title, seo_title: title === 'Home' ? 'Infinite Heroes Comics | Watertown, CT' : `${title} | Infinite Heroes Comics`, seo_description: description, og_image_url: '/assets/images/new-comics.webp', published: true, updated_at: 'fallback' }, sections: sections.map((section, index) => ({ id: `fallback-${slug}-${section.key}`, page_id: `fallback-${slug}`, key: section.key, label: section.label, section_type: section.section_type, content: section.content, sort_order: index, published: true, updated_at: 'fallback' })) });

type PageDataType = 'hero' | 'rich-text' | 'feature-list' | 'image-gallery' | 'call-to-action' | 'cards' | 'events' | 'hours' | 'announcement';

const homeSections: Array<{ key: string; label: string; section_type: PageDataType; content: Record<string, Json> }> = [
  { key: 'hero', label: 'Homepage hero', section_type: 'hero' as const, content: { eyebrow: '01 — Watertown, Connecticut', title: 'Every shelf is a new world.', emphasis: 'new world.', body: 'Paul Santos edited at DC. Now the wall is on Main Street — new comics on Wednesday, collectibles on the floor whenever the door is open.', primaryLabel: 'Visit the shop', primaryHref: '/visit.html', secondaryLabel: 'See what we carry', secondaryHref: '#what-we-carry', imageUrl: '/assets/images/new-comics.webp', imageAlt: 'New comics on the floor at Infinite Heroes', meta: ['Comics', 'Collectibles', 'Main Street'] } },
  { key: 'intro', label: 'Homepage introduction', section_type: 'rich-text' as const, content: { eyebrow: '02 — A home base for fandom', titleLines: ['Find your', 'next', 'favorite.'], body: ['Walk in with a pull list or with nothing but time. Weekly new comics and a wall you can actually browse.', 'Ask at the counter. That is the shop.'] } },
  { key: 'categories', label: 'Homepage categories', section_type: 'cards' as const, content: { eyebrow: '03 — Explore the shop', title: 'Three ways in.', intro: 'New comics, trading cards, and figures on the wall. Same shop. Different rabbit holes.', items: [{ number: '01 / Read', title: 'Comics', label: 'Explore comics', href: '/comics.html', imageUrl: '/assets/images/new-comics.webp', imageAlt: 'New comic books displayed at Infinite Heroes Comics' }, { number: '02 / Play', title: 'Cards', label: 'Explore cards', href: '/cards.html', imageUrl: '/assets/images/trading-cards.webp', imageAlt: 'Trading cards at Infinite Heroes Comics' }, { number: '03 / Display', title: 'Collectibles', label: 'Explore collectibles', href: '/collectibles.html', imageUrl: '/assets/images/collectibles-and-statues.webp', imageAlt: 'Collectible action figures and statues at Infinite Heroes Comics' }] } },
  { key: 'gallery', label: 'Homepage gallery', section_type: 'image-gallery' as const, content: { eyebrow: '04 — Inside Infinite Heroes', title: 'Browse the real thing.', intro: 'New releases, bagged runs, and the wall books that take a longer look. This is a floor, not a catalog.', items: [{ url: '/assets/images/shop-detail-1.webp', alt: 'A selection of bagged comic books on display', caption: 'Stories in every direction.' }, { url: '/assets/images/shop-detail-2.webp', alt: 'A selection of superhero comic books on display', caption: 'Find your next run.' }, { url: '/assets/images/shop-detail-3.webp', alt: 'Shelves of graphic novels at Infinite Heroes Comics', caption: 'Books made to keep.' }, { url: '/assets/images/shop-detail-4.webp', alt: 'Rows of current comic books at Infinite Heroes Comics', caption: 'Something new to see.' }] } },
  { key: 'owner', label: 'Homepage owner story', section_type: 'rich-text' as const, content: { eyebrow: '05 — The story behind the shop', title: 'From DC to Main Street.', body: ['Owner Paul Santos spent more than twenty years in comics, including a run as an editor at DC. He came home to Connecticut and opened Infinite Heroes so the town would have a real shop — not a kiosk.'], buttonLabel: 'Meet the shop', buttonHref: '/about.html', imageUrl: '/assets/images/shop-detail-2.webp', imageAlt: 'Shelves inside Infinite Heroes Comics' } },
  { key: 'visit', label: 'Homepage visit panel', section_type: 'hours' as const, content: { eyebrow: '06 — Find us in Watertown', title: '1098 Main Street.', intro: 'Hours, the address, and a phone that rings the counter.', socialHeading: 'Follow the week.', socialCopy: 'New comics and hours live on @infiniteheroescomics.' } },
  { key: 'cta', label: 'Homepage call to action', section_type: 'call-to-action' as const, content: { eyebrow: '07 — Come by', title: 'Your next favorite is waiting.', body: 'Bring a pull list or just bring time.', buttonLabel: 'Visit the shop', buttonHref: '/visit.html' } },
];

export const fallbackPages: Record<string, CmsPageData> = { home: page('home', 'Home', fallbackPublicSiteData.settings.business_description, homeSections), comics: page('comics', 'Comics', 'New comics, DC, Marvel, and wall books at Infinite Heroes in Watertown, Connecticut.', [{ key: 'hero', label: 'Comics hero', section_type: 'hero', content: { eyebrow: '01 — The wall', title: 'Comics live here.', body: 'Wednesday new comics, DC and Marvel runs, and the books that stay on the wall.', imageUrl: '/assets/images/new-comics.webp', imageAlt: 'New comic books at Infinite Heroes Comics' } }]), cards: page('cards', 'Cards', 'Trading cards and the current card scene at Infinite Heroes Comics in Watertown, Connecticut.', [{ key: 'hero', label: 'Cards hero', section_type: 'hero', content: { eyebrow: '01 — Trading cards', title: 'Find your next pull.', body: 'Trading cards have a place at Infinite Heroes. Check the current card scene, then stop in and see what is on the floor.', imageUrl: '/assets/images/trading-cards.webp', imageAlt: 'Trading cards at Infinite Heroes Comics' } }]), collectibles: page('collectibles', 'Collectibles', 'Figures, statues, and collectibles at Infinite Heroes Comics in Watertown, Connecticut.', [{ key: 'hero', label: 'Collectibles hero', section_type: 'hero', content: { eyebrow: '01 — Display', title: 'Bring fandom home.', body: 'Figures and statues next to the comics — pieces you can take off the shelf.', imageUrl: '/assets/images/collectibles-and-statues.webp', imageAlt: 'Collectibles at Infinite Heroes Comics' } }]), about: page('about', 'About the Shop', 'Paul Santos opened Infinite Heroes Comics in Watertown after a career as a DC Comics editor.', [{ key: 'hero', label: 'About hero', section_type: 'hero', content: { eyebrow: '01 — Origin', title: 'Built for the love of comics.', body: 'An independent shop run by someone who already spent a career inside the books.' } }]), visit: page('visit', 'Visit & Contact', 'Visit Infinite Heroes Comics at 1098 Main Street in Watertown, Connecticut.', [{ key: 'hero', label: 'Visit hero', section_type: 'hero', content: { eyebrow: '01 — Visit', title: '1098 Main Street.', body: 'Watertown’s comic shop. Hours on this page. A phone that rings the counter.' } }]) };


export const fallbackCatalogSections: Record<'comics' | 'collectibles', CatalogSection[]> = {
  comics: [
    { id: 'fallback-comics-new', catalog_type: 'comics', title: 'NEW COMICS', description: 'The weekly drop. Come in on Wednesday or catch the issues that are still on the rack.', image_url: '/assets/images/new-comics.webp', image_alt: 'New comic books at Infinite Heroes Comics', cta_label: 'See new comics', cta_href: '/visit.html', sort_order: 10, enabled: true, created_at: '', updated_at: '' },
    { id: 'fallback-comics-dc', catalog_type: 'comics', title: 'DC & MARVEL', description: 'The big two, plus the indie and mid-list titles that sit next to them.', image_url: '/assets/images/dc-comics.webp', image_alt: 'DC comics at Infinite Heroes Comics', cta_label: 'Browse the wall', cta_href: '/visit.html', sort_order: 20, enabled: true, created_at: '', updated_at: '' },
    { id: 'fallback-comics-graphic', catalog_type: 'comics', title: 'GRAPHIC NOVELS AND WALL BOOKS', description: 'Trades and hardcovers for the longer sit-down, not just the weekly pull.', image_url: '/assets/images/shop-detail-2.webp', image_alt: 'Graphic novels and wall books at Infinite Heroes Comics', cta_label: 'Find a longer read', cta_href: '/visit.html', sort_order: 30, enabled: true, created_at: '', updated_at: '' },
  ],
  collectibles: [
    { id: 'fallback-collectibles-figures', catalog_type: 'collectibles', title: 'FIGURES & STATUES', description: 'Characters and worlds that sit on a shelf, not just in a longbox.', image_url: '/assets/images/collectibles-and-statues.webp', image_alt: 'Figures and statues at Infinite Heroes Comics', cta_label: 'See the display', cta_href: '/visit.html', sort_order: 10, enabled: true, created_at: '', updated_at: '' },
    { id: 'fallback-collectibles-funko', catalog_type: 'collectibles', title: 'FUNKO POP VINYLS', description: 'The recognizable faces, when they are in stock.', image_url: '/assets/images/shop-detail-3.webp', image_alt: 'Funko Pop vinyl figures at Infinite Heroes Comics', cta_label: 'Check availability', cta_href: '/visit.html', sort_order: 20, enabled: true, created_at: '', updated_at: '' },
    { id: 'fallback-collectibles-floor', catalog_type: 'collectibles', title: 'WHAT IS ON THE FLOOR', description: 'Inventory moves. Call or stop in before you drive for one piece.', image_url: '/assets/images/shop-detail-4.webp', image_alt: 'Collectibles on the shop floor at Infinite Heroes Comics', cta_label: 'Plan your visit', cta_href: '/visit.html', sort_order: 30, enabled: true, created_at: '', updated_at: '' },
  ],
};
