import { ActionForm, DeleteForm } from '@/components/admin-action-form';
import { deleteEvent, duplicateEvent, reorderEvent, saveEvent } from '@/app/admin/actions';
import { requireAdmin } from '@/lib/auth';
import { createSupabaseServerClient } from '@/lib/supabase-server';
import type { StoreEvent } from '@/lib/cms';

export const dynamic = 'force-dynamic';
const zone = 'America/New_York';
function inputTime(value: string | null) { if (!value) return ''; const date = new Date(value); const p = Object.fromEntries(new Intl.DateTimeFormat('en-CA', { timeZone: zone, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hourCycle: 'h23' }).formatToParts(date).filter(({ type }) => type !== 'literal').map(({ type, value }) => [type, value])); return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`; }
function EventForm({ event }: { event?: StoreEvent }) { return <ActionForm action={saveEvent}><input type="hidden" name="id" value={event?.id || ''} /><div className="admin-form__grid"><label className="admin-field">Event name<input name="title" maxLength={180} defaultValue={event?.title} required /></label><label className="admin-field">Game/category<input name="category" maxLength={120} defaultValue={event?.category || 'Magic: The Gathering'} required /></label><label className="admin-field">Starts (Eastern)<input name="starts_at" type="datetime-local" defaultValue={inputTime(event?.starts_at || null)} required /></label><label className="admin-field">Ends (optional)<input name="ends_at" type="datetime-local" defaultValue={inputTime(event?.ends_at || null)} /></label><label className="admin-field">Location<input name="location" maxLength={240} defaultValue={event?.location || 'Infinite Heroes Comics'} required /></label><label className="admin-field">Image URL<input name="image_url" type="url" defaultValue={event?.image_url || ''} /></label><label className="admin-field">Image alt text<input name="image_alt" maxLength={250} defaultValue={event?.image_alt || ''} /></label><label className="admin-field">Registration/CTA URL<input name="registration_url" type="url" defaultValue={event?.registration_url || ''} /></label><label className="admin-field">Schedule<select name="recurrence" defaultValue={event?.recurrence || 'none'}><option value="none">One-time event</option><option value="weekly">Weekly recurring</option></select></label><label className="admin-field">Recurring weekday<select name="recurrence_day" defaultValue={String(event?.recurrence_day ?? 5)}><option value="0">Sunday</option><option value="1">Monday</option><option value="2">Tuesday</option><option value="3">Wednesday</option><option value="4">Thursday</option><option value="5">Friday</option><option value="6">Saturday</option></select></label><label className="admin-field">Max occurrences (optional)<input name="max_occurrences" type="number" min="1" max="520" defaultValue={event?.max_occurrences || ''} /></label><label className="admin-field">Display order<input name="sort_order" type="number" min="0" max="999" defaultValue={event?.sort_order ?? 0} /></label></div><label className="admin-field">Description<textarea name="description" maxLength={4000} defaultValue={event?.description || ''} /></label><label className="admin-checkbox"><input name="published" type="checkbox" defaultChecked={event?.published ?? true} /> Active and visible publicly</label></ActionForm>; }
export default async function EventsAdminPage() { await requireAdmin(); const { data } = await (await createSupabaseServerClient()).from('events').select('*').order('sort_order').order('starts_at'); const events = (data ?? []) as StoreEvent[]; return <><header className="admin-header"><div><h1>Events</h1><p>Manage one-time events, recurring schedules, images, registration links, and visibility. Times use {zone}.</p></div></header><section className="admin-panel"><h2>Add event</h2><EventForm /></section><section className="admin-panel"><h2>Event calendar</h2>{events.length === 0 ? <div className="admin-empty">No events have been created yet.</div> : <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Order</th><th>Event</th><th>Schedule</th><th>Status</th><th>Actions</th></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td><ActionForm action={reorderEvent}><input type="hidden" name="id" value={event.id} /><input className="admin-order-input" name="sort_order" type="number" min="0" max="999" defaultValue={event.sort_order} aria-label={`Display order for ${event.title}`} /><button className="admin-button admin-button--quiet" type="submit">Save</button></ActionForm></td><td><strong>{event.title}</strong><br /><small>{event.category} · {event.location}</small></td><td>{event.recurrence === 'weekly' ? `Every ${['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][event.recurrence_day ?? 5]}` : new Intl.DateTimeFormat('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: zone }).format(new Date(event.starts_at))}</td><td>{event.published ? 'Active' : 'Draft'}</td><td className="actions"><details><summary className="admin-button admin-button--quiet">Edit</summary><div className="admin-panel"><EventForm event={event} /></div></details><ActionForm action={duplicateEvent}><input type="hidden" name="id" value={event.id} /><button className="admin-button admin-button--quiet" type="submit">Duplicate</button></ActionForm><DeleteForm action={deleteEvent} id={event.id} /></td></tr>)}</tbody></table></div>}</section></>; }
